version: '3.9'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true" # Enable insecure API for dashboard (make sure to secure this in production)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # Disable exposing every container by default
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.jaridewulf.be`)" # Change jaridewulf.be to your actual domain
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.service=api@internal"

  postgresql:
    image: postgres:15
    container_name: biecht-postgres
    volumes:
      - ./_data/db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4
    container_name: biecht-pgadmin
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "5433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - ./_data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql

  api:
    container_name: biecht-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api-debiecht.jaridewulf.be`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@biecht-postgres:5432/${POSTGRES_DB}
    build:
      context: .
      dockerfile: ./containers/api/Dockerfile
    ports:
      - "3000:3000"
    restart: always

  projection:
    container_name: biecht-projection
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.projection.rule=Host(`projection-debiecht.jaridewulf.be`)"
      - "traefik.http.routers.projection.entrypoints=web"
      - "traefik.http.services.projection.loadbalancer.server.port=80"
    build:
      context: .
      dockerfile: ./containers/projection/Dockerfile
    ports:
      - "3001:80"
    restart: always

  dashboard:
    container_name: biecht-dashboard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard-debiecht.jaridewulf.be`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.services.dashboard.loadbalancer.server.port=80"
    build:
      context: .
      dockerfile: ./containers/dashboard/Dockerfile
    ports:
      - "3002:80"
    restart: always
