version: '3.9'

services:
  postgresql:
    image: postgres:15
    container_name: biecht-postgres
    volumes:
      - ./_data/db:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} 
  pgadmin:
    image: dpage/pgadmin4
    container_name: biecht-pgadmin
    restart: always
    user: "${UID}:${GID}"
    ports:
      - "5433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - ./_data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql